language: node_js
node_js:
- '0.11'
before_install: 
install:
- npm install
script:
- npm run build
- npm run test
- npm run cover
env:
  global:
    secure: bgr5oWqWYsjYo9Nff/7lczdt5hH7CvB62Nalhfi5ADaVyDv4DMpAQUg+/VQAFy/+Ozj+8k/b9YepsPaJ+WD6Q8rKvdBuaQ3+s8HA9tsEn4U5sIQk0yZ9S5pUDs+YTs0KbxuZha9hroE5x31sDuzWnkN05POgZXDo2i13kPFmd/FrHH3S5Z+g2HPSlt9DQSCEQ0rCRMoP9di532+QcXfDUZXfzp66Ykj8vWFi0wiV9B0JG4dA5culYxGJLPHOoVay8hduIiXSalfLeMpNxxmbf6I9IgzlsR56st2J7p/Tdi7yPycP2wHURC6iJVctTkYkX+EfBZPnCwQSfDFS1Xo7/7GtvMgOf8vT83WFenyNtsj0rMLmfdOBi2X6yGzHAtMPjoY6AiQlvv8CPwMpykR363iu8AxTfKjOcDb4FH/Dbku4B8zM9VNQPnG422Yf0I82ay1k56T5KuSAa8csqrRNL6YdM1u1uL9lY5TpncmrnjLeIs9PDoMBmuhyhWylnzYbeNnbUuDA5iLRmE1iQKjMzjJdK8nfSaXyrPDKDmmKkMoFcfOxnqYruoQHHwdQSytBa25rRmdfExZt8rFfNR57jRDxIDxjGjF8kUpM1dgWDGnmkWHc1nJ3WxZSmwBeXP9FcfezYyE0FvBgsKUViv89jsSb1Q8THGinqYhgXW8pkpE=
